### ISSUE TITLE
SerializationException: serializationStream supports seeking, but its length is 0

### ISSUE THREAD

**Issue by slayer3600** [aceade/Unity-Task-List#1]
This is being thrown in the LoadCategories() function in ToDoListPanel.cs when the BinaryFormatter deserializes. I've commented out the line for now and the plugin functions, I'll report back if I have time to resolve.

**Comment by aceade** [comment]
This occurs when the tasks.dat file doesn't exist; I've added some code to fix this.

**Comment by aceade** [comment]
Tested this again on a separate project, and it works. So, I'm closing this as complete.

**Comment by slayer3600** [comment]
Awesome, it does indeed work now thanks!
